import type { Metadata } from "next";

import AuthProvider from "@/providers/authProvider";
import QueryProvider from "@/providers/queryProvider";

import "@/styles/globals.css";
import {
  dmSans,
  geistMono,
  geistSans,
  helveticaNeue,
} from "@/styles/additional-styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${helveticaNeue.variable} ${dmSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>{children}</QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
